config/routes.rb
Rails.application.routes.draw do
  # resources :articles

  get    'articles',          to: 'articles#index'
  get    'articles/new',      to: 'articles#new', as: :new
  post   'articles',          to: 'articles#create'
  get    'articles/:id',      to: 'articles#show', as: :article
  get    'articles/:id/edit', to: 'articles#edit', as: :edit
  patch  'articles/:id',      to: 'articles#update'
  delete 'articles/:id',      to: 'articles#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

<%= link_to "Show", article_path %>
<%= link_to "Back", articles_path %>

app/views/articles/index.html.erb
<h1>Wikinimous</h1>

<%= link_to "New Article", new_path %>

<% @articles.each do |article| %>
<ul>
  <li>
    <p><%= link_to article.title, article %></p>
    <p><%= article.content %></p>
  </li>
</ul>
<% end %>

app/views/articles/new.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

<%= link_to "Back", articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<%= link_to "Edit", edit_path %>
<%= link_to "Delete", article_path(@article),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

 <!-- <img src="https://source.unsplash.com/random" /> -->
<h3><%= @article.content %></h3>
<%= link_to "Back to the list", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>